#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#ifndef APP_VERSION
#define APP_VERSION 1
#endif

#define VERSION_NAME "ZHJS_001"

#define VERSION_FEATURE_OLED_DISPLAY 1
#define VERSION_FEATURE_LIGHT_CONTROL 1
#define VERSION_FEATURE_GL5506 1
#define VERSION_FEATURE_PIR 1
#define VERSION_FEATURE_KEYS 1

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_SENSOR 0x00000008U

#define APP_LIGHT_CHANNEL_COUNT 3U
#define APP_AUTO_LEAVE_DELAY_MS 10000U
#define APP_SENSOR_POLL_MS 200U

#endif
