#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#if defined(PLATFORM_MCS51)
#define VERSION_SCHED_EVENT_TICK (1UL << 0U)
#else
#include "scheduler.h"
#define VERSION_SCHED_EVENT_TICK SCHED_EVENT_TICK
#endif

#ifndef APP_VERSION
#define APP_VERSION 7
#endif

#define VERSION_NAME "SGTZ_001"

#if APP_VERSION == 1
#define VERSION_LABEL "SGTZ-001"
#define VERSION_TITLE "风扇秤"
#elif APP_VERSION == 2
#define VERSION_LABEL "SGTZ-002"
#define VERSION_TITLE "5kg秤"
#elif APP_VERSION == 3
#define VERSION_LABEL "SGTZ-003"
#define VERSION_TITLE "体指秤"
#elif APP_VERSION == 4
#define VERSION_LABEL "SGTZ-004"
#define VERSION_TITLE "蓝牙体指"
#elif APP_VERSION == 5
#define VERSION_LABEL "SGTZ-005"
#define VERSION_TITLE "WiFi体指"
#elif APP_VERSION == 6
#define VERSION_LABEL "SGTZ-006"
#define VERSION_TITLE "视频体指"
#elif APP_VERSION == 7
#define VERSION_LABEL "SGTZ-007"
#define VERSION_TITLE "语音体指"
#else
#error "APP_VERSION must be 1-7"
#endif

#define VERSION_FEATURE_WEIGHT 1
#define VERSION_FEATURE_KEYS 1
#define VERSION_FEATURE_OLED_DISPLAY 1

#if APP_VERSION == 1
#define VERSION_FEATURE_FAN_CONTROL 1
#else
#define VERSION_FEATURE_FAN_CONTROL 0
#endif

#if APP_VERSION == 2
#define VERSION_FEATURE_WEIGHT_ALARM 1
#else
#define VERSION_FEATURE_WEIGHT_ALARM 0
#endif

#if APP_VERSION >= 3
#define VERSION_FEATURE_HEIGHT 1
#define VERSION_FEATURE_BMI 1
#else
#define VERSION_FEATURE_HEIGHT 0
#define VERSION_FEATURE_BMI 0
#endif

#if APP_VERSION == 4
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#if APP_VERSION == 5 || APP_VERSION == 6
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if APP_VERSION == 6
#define VERSION_FEATURE_CAMERA 1
#else
#define VERSION_FEATURE_CAMERA 0
#endif

#if APP_VERSION == 7
#define VERSION_FEATURE_VOICE 1
#define VERSION_FEATURE_BMI_REALTIME 1
#else
#define VERSION_FEATURE_VOICE 0
#define VERSION_FEATURE_BMI_REALTIME 0
#endif

#if VERSION_FEATURE_BLE || VERSION_FEATURE_WIFI
#define VERSION_FEATURE_REMOTE_SPEC 1
#else
#define VERSION_FEATURE_REMOTE_SPEC 0
#endif

#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_HX711 1
#define VERSION_FEATURE_DRIVER_HCSR04 VERSION_FEATURE_HEIGHT
#define VERSION_FEATURE_DRIVER_RELAY VERSION_FEATURE_FAN_CONTROL
#define VERSION_FEATURE_DRIVER_BUZZER (VERSION_FEATURE_WEIGHT_ALARM || VERSION_FEATURE_VOICE)
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT VERSION_FEATURE_WIFI

#include "driver_features.h"

#define APP_EVENT_TICK VERSION_SCHED_EVENT_TICK
#define APP_EVENT_KEY 0x00000004UL
#define APP_EVENT_SENSOR 0x00000008UL
#define APP_EVENT_DISPLAY 0x00000010UL

#define APP_SENSOR_POLL_MS 250U

#endif
