#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#if !defined(APP_VERSION) && defined(RTJK_VERSION)
#define APP_VERSION RTJK_VERSION
#endif

#ifndef APP_VERSION
#define APP_VERSION 10
#endif

#ifndef RTJK_VERSION
#define RTJK_VERSION APP_VERSION
#endif

#define VERSION_NAME "RTJK_001"

#if (APP_VERSION >= 1) && (APP_VERSION <= 7)
#define VERSION_FEATURE_SPO2 1
#else
#define VERSION_FEATURE_SPO2 0
#endif

#if ((APP_VERSION >= 4) && (APP_VERSION <= 7)) || (APP_VERSION >= 9)
#define VERSION_FEATURE_TEMP 1
#else
#define VERSION_FEATURE_TEMP 0
#endif

#if (APP_VERSION == 2) || (APP_VERSION == 5)
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#if (APP_VERSION == 3) || (APP_VERSION == 6) || (APP_VERSION >= 10)
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if APP_VERSION == 7
#define VERSION_FEATURE_VOICE 1
#else
#define VERSION_FEATURE_VOICE 0
#endif

#if APP_VERSION >= 8
#define VERSION_FEATURE_BLOOD_PRESSURE 1
#else
#define VERSION_FEATURE_BLOOD_PRESSURE 0
#endif

#define VERSION_FEATURE_OLED 1
#define VERSION_FEATURE_BUZZER 1
#define VERSION_FEATURE_LED 1
#define VERSION_FEATURE_KEYS 1
#define VERSION_FEATURE_PULSE 1

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_COMM_RX 0x00000002U
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_SENSOR 0x00000008U

#endif
