#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#ifndef RTJK_VERSION
#define RTJK_VERSION 10
#endif

#define VERSION_NAME "RTJK_001"

#if (RTJK_VERSION >= 1) && (RTJK_VERSION <= 7)
#define VERSION_FEATURE_SPO2 1
#else
#define VERSION_FEATURE_SPO2 0
#endif

#if ((RTJK_VERSION >= 4) && (RTJK_VERSION <= 7)) || (RTJK_VERSION >= 9)
#define VERSION_FEATURE_TEMP 1
#else
#define VERSION_FEATURE_TEMP 0
#endif

#if (RTJK_VERSION == 2) || (RTJK_VERSION == 5)
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#if (RTJK_VERSION == 3) || (RTJK_VERSION == 6) || (RTJK_VERSION >= 10)
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if RTJK_VERSION == 7
#define VERSION_FEATURE_VOICE 1
#else
#define VERSION_FEATURE_VOICE 0
#endif

#if RTJK_VERSION >= 8
#define VERSION_FEATURE_BLOOD_PRESSURE 1
#else
#define VERSION_FEATURE_BLOOD_PRESSURE 0
#endif

#define VERSION_FEATURE_OLED 1
#define VERSION_FEATURE_BUZZER 1
#define VERSION_FEATURE_LED 1
#define VERSION_FEATURE_KEYS 1
#define VERSION_FEATURE_PULSE 1

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_COMM_RX 0x00000002U
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_SENSOR 0x00000008U

#endif
