/* RTJK_001 版本能力配置：根据 APP_VERSION 裁剪体温、通讯、语音和血压功能。 */
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#if !defined(APP_VERSION) && defined(RTJK_VERSION)
#define APP_VERSION RTJK_VERSION
#endif

#ifndef APP_VERSION
#define APP_VERSION 10
#endif

#ifndef RTJK_VERSION
#define RTJK_VERSION APP_VERSION
#endif

#define VERSION_NAME "RTJK_001"

#if (APP_VERSION >= 1) && (APP_VERSION <= 7)
#define VERSION_FEATURE_SPO2 1
#else
#define VERSION_FEATURE_SPO2 0
#endif

#if ((APP_VERSION >= 4) && (APP_VERSION <= 7)) || (APP_VERSION >= 9)
#define VERSION_FEATURE_TEMP 1
#else
#define VERSION_FEATURE_TEMP 0
#endif

#if (APP_VERSION == 2) || (APP_VERSION == 5)
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#if (APP_VERSION == 3) || (APP_VERSION == 6) || (APP_VERSION >= 10)
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if APP_VERSION == 7
#define VERSION_FEATURE_VOICE 1
#else
#define VERSION_FEATURE_VOICE 0
#endif

#if APP_VERSION >= 8
#define VERSION_FEATURE_BLOOD_PRESSURE 1
#else
#define VERSION_FEATURE_BLOOD_PRESSURE 0
#endif

#define VERSION_FEATURE_OLED 1
#define VERSION_FEATURE_BUZZER 1
#define VERSION_FEATURE_LED 1
#define VERSION_FEATURE_KEYS 1
#define VERSION_FEATURE_PULSE 1

#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_MAX30102 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_LED 1

#define VERSION_FEATURE_DRIVER_DS18B20 VERSION_FEATURE_TEMP
#define VERSION_FEATURE_DRIVER_JDY31_BLE VERSION_FEATURE_BLE
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_SU03T_VOICE VERSION_FEATURE_VOICE
#define VERSION_FEATURE_DRIVER_MSP20_BP VERSION_FEATURE_BLOOD_PRESSURE

#include "driver_features.h"

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_COMM_RX 0x00000002U
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_SENSOR 0x00000008U

#endif
