#ifndef DRIVER_FEATURES_H
#define DRIVER_FEATURES_H

/*
 * Stable per-driver feature macros.
 *
 * Product version_config.h files define enabled drivers to 1 before including
 * this header. Any driver not selected by the product/version remains 0.
 */

#ifndef VERSION_FEATURE_DRIVER_A7670C_SMS
#define VERSION_FEATURE_DRIVER_A7670C_SMS 0
#endif

#ifndef VERSION_FEATURE_DRIVER_BMP180
#define VERSION_FEATURE_DRIVER_BMP180 0
#endif

#ifndef VERSION_FEATURE_DRIVER_BUZZER
#define VERSION_FEATURE_DRIVER_BUZZER 0
#endif

#ifndef VERSION_FEATURE_DRIVER_CO2_UART
#define VERSION_FEATURE_DRIVER_CO2_UART 0
#endif

#ifndef VERSION_FEATURE_DRIVER_DHT11
#define VERSION_FEATURE_DRIVER_DHT11 0
#endif

#ifndef VERSION_FEATURE_DRIVER_DS1302_RTC
#define VERSION_FEATURE_DRIVER_DS1302_RTC 0
#endif

#ifndef VERSION_FEATURE_DRIVER_DS18B20
#define VERSION_FEATURE_DRIVER_DS18B20 0
#endif

#ifndef VERSION_FEATURE_DRIVER_E18_PRESENCE
#define VERSION_FEATURE_DRIVER_E18_PRESENCE 0
#endif

#ifndef VERSION_FEATURE_DRIVER_ESP8266_MQTT
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT 0
#endif

#ifndef VERSION_FEATURE_DRIVER_ESP8266_WIFI
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI 0
#endif

#ifndef VERSION_FEATURE_DRIVER_GL5506_LIGHT
#define VERSION_FEATURE_DRIVER_GL5506_LIGHT 0
#endif

#ifndef VERSION_FEATURE_DRIVER_HC595_SEG
#define VERSION_FEATURE_DRIVER_HC595_SEG 0
#endif

#ifndef VERSION_FEATURE_DRIVER_HCSR04
#define VERSION_FEATURE_DRIVER_HCSR04 0
#endif

#ifndef VERSION_FEATURE_DRIVER_HX711
#define VERSION_FEATURE_DRIVER_HX711 0
#endif

#ifndef VERSION_FEATURE_DRIVER_IR_CLOTHES
#define VERSION_FEATURE_DRIVER_IR_CLOTHES 0
#endif

#ifndef VERSION_FEATURE_DRIVER_JDY31_BLE
#define VERSION_FEATURE_DRIVER_JDY31_BLE 0
#endif

#ifndef VERSION_FEATURE_DRIVER_KEY
#define VERSION_FEATURE_DRIVER_KEY 0
#endif

#ifndef VERSION_FEATURE_DRIVER_KEY_4CH
#define VERSION_FEATURE_DRIVER_KEY_4CH 0
#endif

#ifndef VERSION_FEATURE_DRIVER_L76K_GNSS
#define VERSION_FEATURE_DRIVER_L76K_GNSS 0
#endif

#ifndef VERSION_FEATURE_DRIVER_LED
#define VERSION_FEATURE_DRIVER_LED 0
#endif

#ifndef VERSION_FEATURE_DRIVER_LIGHT_CHANNEL
#define VERSION_FEATURE_DRIVER_LIGHT_CHANNEL 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MAX30102
#define VERSION_FEATURE_DRIVER_MAX30102 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MPU6050
#define VERSION_FEATURE_DRIVER_MPU6050 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MQ135
#define VERSION_FEATURE_DRIVER_MQ135 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MQ2_SMOKE
#define VERSION_FEATURE_DRIVER_MQ2_SMOKE 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MQ4_METHANE
#define VERSION_FEATURE_DRIVER_MQ4_METHANE 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MQ7_CO
#define VERSION_FEATURE_DRIVER_MQ7_CO 0
#endif

#ifndef VERSION_FEATURE_DRIVER_MSP20_BP
#define VERSION_FEATURE_DRIVER_MSP20_BP 0
#endif

#ifndef VERSION_FEATURE_DRIVER_NRF24L01
#define VERSION_FEATURE_DRIVER_NRF24L01 0
#endif

#ifndef VERSION_FEATURE_DRIVER_OLED_FONT
#define VERSION_FEATURE_DRIVER_OLED_FONT 0
#endif

#ifndef VERSION_FEATURE_DRIVER_OLED_SSD1306
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 0
#endif

#ifndef VERSION_FEATURE_DRIVER_PH_SENSOR
#define VERSION_FEATURE_DRIVER_PH_SENSOR 0
#endif

#ifndef VERSION_FEATURE_DRIVER_PM25
#define VERSION_FEATURE_DRIVER_PM25 0
#endif

#ifndef VERSION_FEATURE_DRIVER_RELAY
#define VERSION_FEATURE_DRIVER_RELAY 0
#endif

#ifndef VERSION_FEATURE_DRIVER_RFID_RC522
#define VERSION_FEATURE_DRIVER_RFID_RC522 0
#endif

#ifndef VERSION_FEATURE_DRIVER_SG90
#define VERSION_FEATURE_DRIVER_SG90 0
#endif

#ifndef VERSION_FEATURE_DRIVER_STEPMOTOR
#define VERSION_FEATURE_DRIVER_STEPMOTOR 0
#endif

#ifndef VERSION_FEATURE_DRIVER_SU03T_VOICE
#define VERSION_FEATURE_DRIVER_SU03T_VOICE 0
#endif

#ifndef VERSION_FEATURE_DRIVER_WATER_LEVEL
#define VERSION_FEATURE_DRIVER_WATER_LEVEL 0
#endif

#endif
