
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

/* 固件版本入口：APP_VERSION 由 CMake 传入，默认按基础版 v1 编译。 */
#ifndef APP_VERSION
#define APP_VERSION 1
#endif

#define VERSION_NAME "ZNLYJ_001"

/* 产品功能开关：业务层根据这些宏裁剪传感器、执行器和远程通讯逻辑。 */
#define VERSION_FEATURE_OLED_DISPLAY 1
#define VERSION_FEATURE_TEMP_HUM_SENSOR 1
#define VERSION_FEATURE_PRESENCE 1
#define VERSION_FEATURE_IR_CLOTHES 1
#define VERSION_FEATURE_STEPPER 1
#define VERSION_FEATURE_KEYS 1

#if APP_VERSION >= 2
#define VERSION_FEATURE_LIGHT 1
#define VERSION_FEATURE_WEIGHT 1
#else
#define VERSION_FEATURE_LIGHT 0
#define VERSION_FEATURE_WEIGHT 0
#endif

#if APP_VERSION == 3
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#if APP_VERSION == 4
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if VERSION_FEATURE_WIFI || VERSION_FEATURE_BLE
#define VERSION_FEATURE_REMOTE 1
#else
#define VERSION_FEATURE_REMOTE 0
#endif

/* 驱动自注册裁剪宏：未在这里启用的驱动由 driver_features.h 统一补 0。 */
#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_DHT11 1
#define VERSION_FEATURE_DRIVER_E18_PRESENCE 1
#define VERSION_FEATURE_DRIVER_IR_CLOTHES 1
#define VERSION_FEATURE_DRIVER_STEPMOTOR 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_KEY 1

#define VERSION_FEATURE_DRIVER_GL5506_LIGHT VERSION_FEATURE_LIGHT
#define VERSION_FEATURE_DRIVER_HX711 VERSION_FEATURE_WEIGHT
#define VERSION_FEATURE_DRIVER_JDY31_BLE VERSION_FEATURE_BLE
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT VERSION_FEATURE_WIFI

#include "driver_features.h"

/* 应用事件位：调度循环通过这些事件触发按键、采样、通讯和遥测发送。 */
#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_SENSOR 0x00000008U
#define APP_EVENT_COMM_RX 0x00000010U
#define APP_EVENT_COMM_TX 0x00000020U

#define APP_SENSOR_POLL_MS 500U
#define APP_TELEMETRY_INTERVAL_MS 3000U

#endif
