/* driver_all_test 版本能力配置：尽量启用全部驱动宏，用于驱动目录集成验证。 */
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#ifndef APP_VERSION
#define APP_VERSION 1
#endif

#define VERSION_NAME "driver_all_test"

#define VERSION_FEATURE_DRIVER_A7670C_SMS 1
#define VERSION_FEATURE_DRIVER_BMP180 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_CO2_UART 1
#define VERSION_FEATURE_DRIVER_DHT11 1
#define VERSION_FEATURE_DRIVER_DS1302_RTC 1
#define VERSION_FEATURE_DRIVER_DS18B20 1
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT 1
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI 1
#define VERSION_FEATURE_DRIVER_HC595_SEG 1
#define VERSION_FEATURE_DRIVER_HCSR04 1
#define VERSION_FEATURE_DRIVER_HX711 1
#define VERSION_FEATURE_DRIVER_JDY31_BLE 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_L76K_GNSS 1
#define VERSION_FEATURE_DRIVER_LED 1
#define VERSION_FEATURE_DRIVER_MAX30102 1
#define VERSION_FEATURE_DRIVER_MPU6050 1
#define VERSION_FEATURE_DRIVER_MQ2_SMOKE 1
#define VERSION_FEATURE_DRIVER_MQ4_METHANE 1
#define VERSION_FEATURE_DRIVER_MQ7_CO 1
#define VERSION_FEATURE_DRIVER_MSP20_BP 0
#define VERSION_FEATURE_DRIVER_NRF24L01 1
#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_PH_SENSOR 1
#define VERSION_FEATURE_DRIVER_PM25 1
#define VERSION_FEATURE_DRIVER_RELAY 1
#define VERSION_FEATURE_DRIVER_RFID_RC522 1
#define VERSION_FEATURE_DRIVER_SG90 1
#define VERSION_FEATURE_DRIVER_STEPMOTOR 1
#define VERSION_FEATURE_DRIVER_SU03T_VOICE 1
#define VERSION_FEATURE_DRIVER_WATER_LEVEL 1

#include "driver_features.h"

#define APP_EVENT_TICK SCHED_EVENT_TICK

#endif
