/* DCLD_001 版本能力配置：根据 APP_VERSION 裁剪温度补偿、语音、通讯和摄像头功能。 */
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#if !defined(APP_VERSION) && defined(DCLD_VERSION)
#define APP_VERSION DCLD_VERSION
#endif

#ifndef APP_VERSION
#define APP_VERSION 7
#endif

#ifndef DCLD_VERSION
#define DCLD_VERSION APP_VERSION
#endif

#define VERSION_NAME "DCLD_001"

#if APP_VERSION >= 2
#define VERSION_FEATURE_TEMP_COMP 1
#else
#define VERSION_FEATURE_TEMP_COMP 0
#endif

#if (APP_VERSION == 3) || (APP_VERSION == 6) || (APP_VERSION == 7)
#define VERSION_FEATURE_VOICE 1
#else
#define VERSION_FEATURE_VOICE 0
#endif

#if (APP_VERSION == 4) || (APP_VERSION == 6) || (APP_VERSION == 7)
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if APP_VERSION == 5
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#if APP_VERSION >= 4
#define VERSION_FEATURE_REMOTE 1
#else
#define VERSION_FEATURE_REMOTE 0
#endif

#if APP_VERSION == 7
#define VERSION_FEATURE_CAMERA 1
#else
#define VERSION_FEATURE_CAMERA 0
#endif

#define DCLD_HAS_TEMP_COMP VERSION_FEATURE_TEMP_COMP
#define DCLD_HAS_VOICE VERSION_FEATURE_VOICE
#define DCLD_HAS_WIFI VERSION_FEATURE_WIFI
#define DCLD_HAS_BLE VERSION_FEATURE_BLE
#define DCLD_HAS_REMOTE VERSION_FEATURE_REMOTE
#define DCLD_HAS_CAMERA VERSION_FEATURE_CAMERA

#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_HCSR04 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_LED 1

#define VERSION_FEATURE_DRIVER_DS18B20 VERSION_FEATURE_TEMP_COMP
#define VERSION_FEATURE_DRIVER_SU03T_VOICE VERSION_FEATURE_VOICE
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_JDY31_BLE VERSION_FEATURE_BLE

#include "driver_features.h"

#define APP_EVENT_TICK        SCHED_EVENT_TICK
#define APP_EVENT_KEY         0x02U
#define APP_EVENT_SENSOR      0x04U
#define APP_EVENT_ALARM       0x08U
#define APP_EVENT_COMM_RX     0x10U
#define APP_EVENT_COMM_TX     0x20U

#endif
