#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#ifndef APP_VERSION
#define APP_VERSION 24
#endif

#define VERSION_NAME "YYYH_001"

#define VERSION_FEATURE_STM32 (APP_VERSION >= 5)
#define VERSION_FEATURE_BLE ((APP_VERSION == 2) || (APP_VERSION == 6) || (APP_VERSION == 11) || (APP_VERSION == 16) || (APP_VERSION == 21))
#define VERSION_FEATURE_WIFI ((APP_VERSION == 3) || (APP_VERSION == 4) || (APP_VERSION == 7) || (APP_VERSION == 8) || \
                              (APP_VERSION == 12) || (APP_VERSION == 13) || (APP_VERSION == 17) || (APP_VERSION == 18) || \
                              (APP_VERSION == 22) || (APP_VERSION == 23))
#define VERSION_FEATURE_CAMERA ((APP_VERSION == 4) || (APP_VERSION == 8) || (APP_VERSION == 13) || (APP_VERSION == 18) || (APP_VERSION == 23))
#define VERSION_FEATURE_CLOUD ((APP_VERSION == 9) || (APP_VERSION == 14) || (APP_VERSION == 19) || (APP_VERSION == 24))
#define VERSION_FEATURE_REMOTE (VERSION_FEATURE_BLE || VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)
#define VERSION_FEATURE_SERVO (APP_VERSION >= 5)
#define VERSION_FEATURE_WEIGHT (APP_VERSION >= 10)
#define VERSION_FEATURE_VOICE (APP_VERSION >= 15)
#define VERSION_FEATURE_DHT11 (APP_VERSION >= 20)

#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_LED 1
#define VERSION_FEATURE_DRIVER_DS1302 1
#define VERSION_FEATURE_DRIVER_E18_PRESENCE 1
#define VERSION_FEATURE_DRIVER_SG90 VERSION_FEATURE_SERVO
#define VERSION_FEATURE_DRIVER_HX711 VERSION_FEATURE_WEIGHT
#define VERSION_FEATURE_DRIVER_DHT11 VERSION_FEATURE_DHT11
#define VERSION_FEATURE_DRIVER_TTS_UART VERSION_FEATURE_VOICE
#define VERSION_FEATURE_DRIVER_JDY31_BLE VERSION_FEATURE_BLE
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI (VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT (VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_KEY 0x00000004UL
#define APP_EVENT_RTC 0x00000008UL
#define APP_EVENT_SENSOR 0x00000010UL
#define APP_EVENT_ALARM 0x00000020UL
#define APP_EVENT_DISPLAY 0x00000040UL
#define APP_EVENT_COMM_RX 0x00000080UL
#define APP_EVENT_COMM_TX 0x00000100UL

#endif

