/* ZNCZ_001 版本能力配置：启用 OLED、继电器、WiFi、RTC、按键和定时模式。 */
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#ifndef APP_VERSION
#define APP_VERSION 1
#endif

#define VERSION_NAME "ZNCZ_001"

#define VERSION_FEATURE_OLED_DISPLAY 1
#define VERSION_FEATURE_RELAY 1
#define VERSION_FEATURE_WIFI 1
#define VERSION_FEATURE_RTC 1
#define VERSION_FEATURE_KEYS 1
#define VERSION_FEATURE_TIMER_MODE 1

#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_RELAY 1
#define VERSION_FEATURE_DRIVER_DS1302_RTC 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI 1
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT 1
#define VERSION_FEATURE_DRIVER_LED 1

#include "driver_features.h"

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_COMM_RX 0x00000002U
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_DISPLAY 0x00000008U

#endif
