#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#define VERSION_NAME "ZNCZ_001"

#define VERSION_FEATURE_OLED_DISPLAY 1
#define VERSION_FEATURE_RELAY 1
#define VERSION_FEATURE_WIFI 1
#define VERSION_FEATURE_RTC 1
#define VERSION_FEATURE_KEYS 1
#define VERSION_FEATURE_TIMER_MODE 1

#define APP_EVENT_TICK SCHED_EVENT_TICK
#define APP_EVENT_COMM_RX 0x00000002U
#define APP_EVENT_KEY 0x00000004U
#define APP_EVENT_DISPLAY 0x00000008U

#endif
