/* FJXT_001 版本能力配置：根据 APP_VERSION 裁剪蓝牙、WiFi、视频、云平台和语音播报功能。 */
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#ifndef APP_VERSION
#define APP_VERSION 1
#endif

#define VERSION_NAME "FJXT_001"

#define VERSION_FEATURE_BLE ((APP_VERSION == 2) || (APP_VERSION == 7))
#define VERSION_FEATURE_WIFI ((APP_VERSION == 3) || (APP_VERSION == 4) || (APP_VERSION == 8) || (APP_VERSION == 9))
#define VERSION_FEATURE_CAMERA ((APP_VERSION == 4) || (APP_VERSION == 9))
#define VERSION_FEATURE_CLOUD ((APP_VERSION == 5) || (APP_VERSION == 10))
#define VERSION_FEATURE_REMOTE (VERSION_FEATURE_BLE || VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)
#define VERSION_FEATURE_VOICE (APP_VERSION >= 6)

#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_STEPMOTOR 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_LED 1
#define VERSION_FEATURE_DRIVER_JDY31_BLE VERSION_FEATURE_BLE
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI (VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT (VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)
#define VERSION_FEATURE_DRIVER_SU03T_VOICE VERSION_FEATURE_VOICE

#endif
