# 从 hal_options.cmake 扫描 HAL option() 与 list(APPEND *_SRC) 变量名，供导出解析复用。

function(hal_export_scan_metadata hal_options_file out_options_var out_groups_var)
    if(NOT EXISTS "${hal_options_file}")
        message(FATAL_ERROR "hal_options.cmake not found: ${hal_options_file}")
    endif()

    file(STRINGS "${hal_options_file}" _lines)
    set(_opts "")
    set(_groups "")

    foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if(_line MATCHES "^option\\(HAL_([A-Z0-9_]+)")
            list(APPEND _opts "HAL_${CMAKE_MATCH_1}")
        endif()
        if(_line MATCHES "list\\(APPEND[ \t]+([A-Z0-9_]+_SRC)[ \t]")
            list(APPEND _groups "${CMAKE_MATCH_1}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _opts)
    list(REMOVE_DUPLICATES _groups)
    set(${out_options_var} "${_opts}" PARENT_SCOPE)
    set(${out_groups_var} "${_groups}" PARENT_SCOPE)
endfunction()

function(hal_export_emit hal_options_list hal_groups_list)
    foreach(_group IN LISTS hal_groups_list)
        if(DEFINED ${_group})
            foreach(_item IN LISTS ${_group})
                message("EXPORT_HAL_SRC:${_group}:${_item}")
            endforeach()
        endif()
    endforeach()

    foreach(_opt IN LISTS hal_options_list)
        if(${_opt})
            message("EXPORT_HAL_DEFINE:${_opt}=1")
        else()
            message("EXPORT_HAL_DEFINE:${_opt}=0")
        endif()
    endforeach()
endfunction()
