option(HAL_I2C_USE_SOFT "Use software I2C (GPIO bit-bang) instead of hardware I2C" OFF)
option(HAL_SPI_USE_SOFT "Compile software SPI module" OFF)
option(HAL_SPI_USE_HW "Compile hardware SPI module (SPL)" OFF)
option(HAL_SPI_ENABLE_DMA "Enable hardware SPI DMA TX/RX (requires HAL_SPI_USE_HW)" OFF)
option(HAL_USART_ENABLE_DMA "Enable USART DMA TX support" OFF)
option(HAL_ADC_ENABLE "Enable ADC polling acquisition" OFF)
option(HAL_ADC_ENABLE_DMA "Enable ADC DMA continuous acquisition (requires HAL_ADC_ENABLE)" OFF)
option(HAL_DEBUG_UART_ENABLE "Enable GPIO bit-bang debug UART TX (printf via _write)" OFF)

if(HAL_SPI_USE_SOFT AND HAL_SPI_USE_HW)
    message(FATAL_ERROR "HAL_SPI_USE_SOFT and HAL_SPI_USE_HW are mutually exclusive")
endif()

if(HAL_SPI_ENABLE_DMA AND NOT HAL_SPI_USE_HW)
    message(FATAL_ERROR "HAL_SPI_ENABLE_DMA requires HAL_SPI_USE_HW=ON")
endif()

if(HAL_ADC_ENABLE_DMA AND NOT HAL_ADC_ENABLE)
    message(FATAL_ERROR "HAL_ADC_ENABLE_DMA requires HAL_ADC_ENABLE=ON")
endif()

if(HAL_I2C_USE_SOFT)
    list(APPEND BSP_HAL_I2C_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/i2c_hal_soft.c)
else()
    list(APPEND BSP_HAL_I2C_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/i2c_hal_hw.c)
    list(APPEND SPL_HAL_I2C_SRC ${TEMPLATE_ROOT}/bsp/stm32f10x_std_lib/Libraries/FWlib/src/stm32f10x_i2c.c)
endif()

if(HAL_SPI_USE_SOFT)
    list(APPEND BSP_HAL_SPI_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/spi_hal_soft.c)
endif()

if(HAL_SPI_USE_HW)
    list(APPEND BSP_HAL_SPI_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/spi_hal_hw.c)
    list(APPEND SPL_HAL_SPI_SRC ${TEMPLATE_ROOT}/bsp/stm32f10x_std_lib/Libraries/FWlib/src/stm32f10x_spi.c)
    if(HAL_SPI_ENABLE_DMA)
        list(APPEND BSP_HAL_SPI_DMA_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/spi_hal_dma.c)
    endif()
endif()

if(HAL_USART_ENABLE_DMA)
    list(APPEND BSP_HAL_USART_DMA_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/usart_hal_dma.c)
endif()

if(HAL_ADC_ENABLE)
    list(APPEND BSP_HAL_ADC_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/adc_hal.c)
    list(APPEND SPL_HAL_ADC_SRC ${TEMPLATE_ROOT}/bsp/stm32f10x_std_lib/Libraries/FWlib/src/stm32f10x_adc.c)
    if(HAL_ADC_ENABLE_DMA)
        list(APPEND BSP_HAL_ADC_DMA_SRC ${TEMPLATE_ROOT}/bsp/hal_wrapper/adc_hal_dma.c)
    endif()
endif()

if(HAL_USART_ENABLE_DMA OR HAL_SPI_ENABLE_DMA OR HAL_ADC_ENABLE_DMA)
    list(APPEND SPL_HAL_DMA_SRC ${TEMPLATE_ROOT}/bsp/stm32f10x_std_lib/Libraries/FWlib/src/stm32f10x_dma.c)
endif()

function(hal_apply_compile_definitions target_name)
    if(HAL_I2C_USE_SOFT)
        target_compile_definitions(${target_name} PRIVATE HAL_I2C_USE_SOFT=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_I2C_USE_SOFT=0)
    endif()

    if(HAL_SPI_USE_SOFT)
        target_compile_definitions(${target_name} PRIVATE HAL_SPI_USE_SOFT=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_SPI_USE_SOFT=0)
    endif()

    if(HAL_SPI_USE_HW)
        target_compile_definitions(${target_name} PRIVATE HAL_SPI_USE_HW=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_SPI_USE_HW=0)
    endif()

    if(HAL_SPI_ENABLE_DMA)
        target_compile_definitions(${target_name} PRIVATE HAL_SPI_ENABLE_DMA=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_SPI_ENABLE_DMA=0)
    endif()

    if(HAL_USART_ENABLE_DMA)
        target_compile_definitions(${target_name} PRIVATE HAL_USART_ENABLE_DMA=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_USART_ENABLE_DMA=0)
    endif()

    if(HAL_ADC_ENABLE)
        target_compile_definitions(${target_name} PRIVATE HAL_ADC_ENABLE=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_ADC_ENABLE=0)
    endif()

    if(HAL_ADC_ENABLE_DMA)
        target_compile_definitions(${target_name} PRIVATE HAL_ADC_ENABLE_DMA=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_ADC_ENABLE_DMA=0)
    endif()

    if(HAL_DEBUG_UART_ENABLE)
        target_compile_definitions(${target_name} PRIVATE HAL_DEBUG_UART_ENABLE=1)
    else()
        target_compile_definitions(${target_name} PRIVATE HAL_DEBUG_UART_ENABLE=0)
    endif()
endfunction()
