set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(STM32_TOOLCHAIN_BIN "D:/ProgramFile/ST/STM32CubeCLT_1.20.0/GNU-tools-for-STM32/bin" CACHE PATH "STM32 GNU toolchain bin directory")

set(CMAKE_C_COMPILER "${STM32_TOOLCHAIN_BIN}/arm-none-eabi-gcc.exe" CACHE FILEPATH "ARM GCC C compiler")
set(CMAKE_ASM_COMPILER "${STM32_TOOLCHAIN_BIN}/arm-none-eabi-gcc.exe" CACHE FILEPATH "ARM GCC ASM compiler")
set(CMAKE_OBJCOPY "${STM32_TOOLCHAIN_BIN}/arm-none-eabi-objcopy.exe" CACHE FILEPATH "ARM objcopy")
set(CMAKE_SIZE "${STM32_TOOLCHAIN_BIN}/arm-none-eabi-size.exe" CACHE FILEPATH "ARM size")

set(CMAKE_FIND_ROOT_PATH "${STM32_TOOLCHAIN_BIN}/..")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
