/* KQZL3 版本能力配置：根据 APP_VERSION 裁剪 DHT11、MQ 系列和远程通讯功能。 */
#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#include "scheduler.h"

#ifndef APP_VERSION
#define APP_VERSION 14
#endif

#define VERSION_NAME "KQZL3"

#if APP_VERSION >= 2
#define VERSION_FEATURE_DHT11 1
#else
#define VERSION_FEATURE_DHT11 0
#endif

#if APP_VERSION >= 5
#define VERSION_FEATURE_MQ2 1
#else
#define VERSION_FEATURE_MQ2 0
#endif

#if APP_VERSION >= 11
#define VERSION_FEATURE_MQ7 1
#else
#define VERSION_FEATURE_MQ7 0
#endif

#if (APP_VERSION == 3) || (APP_VERSION == 6) || (APP_VERSION == 8) || \
    (APP_VERSION == 9) || (APP_VERSION == 10) || (APP_VERSION == 12) || \
    (APP_VERSION == 14)
#define VERSION_FEATURE_WIFI 1
#else
#define VERSION_FEATURE_WIFI 0
#endif

#if (APP_VERSION == 4) || (APP_VERSION == 7) || (APP_VERSION == 13)
#define VERSION_FEATURE_BLE 1
#else
#define VERSION_FEATURE_BLE 0
#endif

#define VERSION_FEATURE_DRIVER_OLED_FONT 1
#define VERSION_FEATURE_DRIVER_OLED_SSD1306 1
#define VERSION_FEATURE_DRIVER_RELAY 1
#define VERSION_FEATURE_DRIVER_BUZZER 1
#define VERSION_FEATURE_DRIVER_LED 1
#define VERSION_FEATURE_DRIVER_KEY 1
#define VERSION_FEATURE_DRIVER_PM25 1

#define VERSION_FEATURE_DRIVER_DHT11 VERSION_FEATURE_DHT11
#define VERSION_FEATURE_DRIVER_ESP8266_WIFI VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_ESP8266_MQTT VERSION_FEATURE_WIFI
#define VERSION_FEATURE_DRIVER_JDY31_BLE VERSION_FEATURE_BLE
#define VERSION_FEATURE_DRIVER_MQ2_SMOKE VERSION_FEATURE_MQ2
#define VERSION_FEATURE_DRIVER_MQ7_CO VERSION_FEATURE_MQ7

#include "driver_features.h"

#define APP_EVENT_TICK          SCHED_EVENT_TICK
#define APP_EVENT_KEY           0x02
#define APP_EVENT_SENSOR_READY  0x04
#define APP_EVENT_COMM_RX       0x08
#define APP_EVENT_ALARM_TRIGGER 0x10
#define APP_EVENT_COMM_TX       0x20

#endif
