#ifndef CJSON_CONFIG_H
#define CJSON_CONFIG_H

/*
 * cJSON 嵌入式裁剪配置。
 * 设为 0 可恢复完整 upstream API（仅保留本文件中的 CJSON_NESTING_LIMIT 等通用项）。
 */
#ifndef CJSON_EMBEDDED_MINIMAL
#define CJSON_EMBEDDED_MINIMAL 1
#endif

#ifndef CJSON_NESTING_LIMIT
#define CJSON_NESTING_LIMIT 32
#endif

#if CJSON_EMBEDDED_MINIMAL

#ifndef CJSON_DISABLE_VERSION
#define CJSON_DISABLE_VERSION 1
#endif
#ifndef CJSON_DISABLE_GET_HELPERS
#define CJSON_DISABLE_GET_HELPERS 1
#endif
#ifndef CJSON_DISABLE_SET_HELPERS
#define CJSON_DISABLE_SET_HELPERS 1
#endif
#ifndef CJSON_DISABLE_PARSE_API
#define CJSON_DISABLE_PARSE_API 1
#endif
#ifndef CJSON_DISABLE_FORMATTED_PRINT
#define CJSON_DISABLE_FORMATTED_PRINT 1
#endif
#ifndef CJSON_DISABLE_PRINT_BUFFERED
#define CJSON_DISABLE_PRINT_BUFFERED 1
#endif
#ifndef CJSON_DISABLE_ARRAYS
#define CJSON_DISABLE_ARRAYS 1
#endif
#ifndef CJSON_DISABLE_RAW
#define CJSON_DISABLE_RAW 1
#endif
#ifndef CJSON_DISABLE_BOOL_NULL_PRINT
#define CJSON_DISABLE_BOOL_NULL_PRINT 1
#endif
#ifndef CJSON_DISABLE_ARRAY_API
#define CJSON_DISABLE_ARRAY_API 1
#endif
#ifndef CJSON_DISABLE_UTILS
#define CJSON_DISABLE_UTILS 1
#endif
#ifndef CJSON_DISABLE_CREATE_EXTRAS
#define CJSON_DISABLE_CREATE_EXTRAS 1
#endif
#ifndef CJSON_DISABLE_REFERENCE
#define CJSON_DISABLE_REFERENCE 1
#endif
#ifndef CJSON_DISABLE_DUPLICATE
#define CJSON_DISABLE_DUPLICATE 1
#endif
#ifndef CJSON_DISABLE_MINIFY
#define CJSON_DISABLE_MINIFY 1
#endif
#ifndef CJSON_DISABLE_COMPARE
#define CJSON_DISABLE_COMPARE 1
#endif
#ifndef CJSON_DISABLE_IS_HELPERS
#define CJSON_DISABLE_IS_HELPERS 1
#endif

#else /* !CJSON_EMBEDDED_MINIMAL */

#ifndef CJSON_DISABLE_VERSION
#define CJSON_DISABLE_VERSION 0
#endif
#ifndef CJSON_DISABLE_GET_HELPERS
#define CJSON_DISABLE_GET_HELPERS 0
#endif
#ifndef CJSON_DISABLE_SET_HELPERS
#define CJSON_DISABLE_SET_HELPERS 0
#endif
#ifndef CJSON_DISABLE_PARSE_API
#define CJSON_DISABLE_PARSE_API 0
#endif
#ifndef CJSON_DISABLE_FORMATTED_PRINT
#define CJSON_DISABLE_FORMATTED_PRINT 0
#endif
#ifndef CJSON_DISABLE_PRINT_BUFFERED
#define CJSON_DISABLE_PRINT_BUFFERED 0
#endif
#ifndef CJSON_DISABLE_ARRAYS
#define CJSON_DISABLE_ARRAYS 0
#endif
#ifndef CJSON_DISABLE_RAW
#define CJSON_DISABLE_RAW 0
#endif
#ifndef CJSON_DISABLE_BOOL_NULL_PRINT
#define CJSON_DISABLE_BOOL_NULL_PRINT 0
#endif
#ifndef CJSON_DISABLE_ARRAY_API
#define CJSON_DISABLE_ARRAY_API 0
#endif
#ifndef CJSON_DISABLE_UTILS
#define CJSON_DISABLE_UTILS 0
#endif
#ifndef CJSON_DISABLE_CREATE_EXTRAS
#define CJSON_DISABLE_CREATE_EXTRAS 0
#endif
#ifndef CJSON_DISABLE_REFERENCE
#define CJSON_DISABLE_REFERENCE 0
#endif
#ifndef CJSON_DISABLE_DUPLICATE
#define CJSON_DISABLE_DUPLICATE 0
#endif
#ifndef CJSON_DISABLE_MINIFY
#define CJSON_DISABLE_MINIFY 0
#endif
#ifndef CJSON_DISABLE_COMPARE
#define CJSON_DISABLE_COMPARE 0
#endif
#ifndef CJSON_DISABLE_IS_HELPERS
#define CJSON_DISABLE_IS_HELPERS 0
#endif

#endif /* CJSON_EMBEDDED_MINIMAL */

#endif /* CJSON_CONFIG_H */
