#ifndef VERSION_CONFIG_H
#define VERSION_CONFIG_H

#ifndef APP_VERSION
#define APP_VERSION 15
#endif

#define VERSION_FEATURE_BLE \
    ((APP_VERSION == 2) || (APP_VERSION == 7) || (APP_VERSION == 12))

#define VERSION_FEATURE_WIFI \
    ((APP_VERSION == 3) || (APP_VERSION == 4) || (APP_VERSION == 8) || \
     (APP_VERSION == 9) || (APP_VERSION == 13) || (APP_VERSION == 14))

#define VERSION_FEATURE_CLOUD \
    ((APP_VERSION == 5) || (APP_VERSION == 10) || (APP_VERSION == 15))

#define VERSION_FEATURE_REMOTE \
    (VERSION_FEATURE_BLE || VERSION_FEATURE_WIFI || VERSION_FEATURE_CLOUD)

#define VERSION_FEATURE_VIDEO \
    ((APP_VERSION == 4) || (APP_VERSION == 9) || (APP_VERSION == 14))

#define VERSION_FEATURE_LIGHT \
    ((APP_VERSION >= 6) && (APP_VERSION <= 16))

#define VERSION_FEATURE_MESSAGE \
    ((APP_VERSION >= 11) && (APP_VERSION <= 15))

#define VERSION_FEATURE_LCD1602_SUBSET \
    (APP_VERSION == 16)

#define VERSION_FEATURE_IR_REMOTE \
    (APP_VERSION == 18)

#define VERSION_FEATURE_TTS \
    ((APP_VERSION >= 1) && (APP_VERSION <= 15))

#define VERSION_FEATURE_UNSUPPORTED_51 \
    (APP_VERSION == 17)

#endif
